### ISSUE TITLE
I made a logo

### ISSUE THREAD

**Issue by Centril** [proptest-rs/proptest#105]
http://diesel.rs/ and https://rocket.rs/ have nice logos so I spent a bit of time designing a logo and finally came up with this:

![proptest2-simple2](https://user-images.githubusercontent.com/855702/48046772-f022f680-e195-11e8-83ef-a0e562d54fee.png)

with color:

![proptest4-green](https://user-images.githubusercontent.com/855702/48048813-f9639180-e19c-11e8-8cba-c8872178fc38.png)

with "woosh":

![proptest3-woosh](https://user-images.githubusercontent.com/855702/48048840-0da78e80-e19d-11e8-88c0-e2aa6d53857c.png)

and color:

![proptest4-woosh](https://user-images.githubusercontent.com/855702/48048953-68d98100-e19d-11e8-82d6-b823ec27676e.png)

What do you think?

Spoiler:

<details>
It's basically \forall and a P
</details>

**Comment by mulkieran** [comment]
It's so comparatively easy to way in on logos that I feel kind of ashamed when I do it, but I do have an opinion. \forall is a good idea. \forall + p makes sense. "whoosh" looks bad. two-colour doesn't really make it more interesting. Maybe there is some talented artist about who could oxidize the logo a bit and give it more character? That would be great!

**Comment by Centril** [comment]
Here are the illustrator files (for the talented artist):
+ https://drive.google.com/file/d/13bvTYumbTWMFvLFyDgDrrYFYaGazAWiM/view?usp=sharing
+ https://drive.google.com/file/d/1ATF-81NIowWgx5Um9rHCdqlQzk7re26M/view?usp=sharing

Some design thoughts I had:
- I went with green to symbolize "all tests passed" =P
- I tried to go with "elegant" and "timeless" with the design.

**Comment by AltSysrq** [comment]
First thoughts from me:

- I like the high-level concept.

- The dark grey is almost exactly the same colour as the comment background in the [GitHub dark theme](https://userstyles.org/styles/37035/github-dark). Admittedly other logos, including the Rust logo itself, have the same issue.

- I think the problem with the "whoosh" is that it's the only curved element in the design despite being a minor element. It's also attached to the P which makes it look more like hair to me. Straight lines not connected to the body might work ([example](https://upload.wikimedia.org/wikipedia/commons/2/23/Go_Logo_Aqua.svg)).

**Comment by AltSysrq** [comment]
Just a random idea I had. It replaces the top of the P with a cycloidal gear, and extends the cross stroke in an attempt to get more horizontal balance. (Disregard the exact colour here, I used OpenSCAD to produce this since it was convenient and that's just what it outputs.)

![logo](https://user-images.githubusercontent.com/1392512/48109575-3ebba980-e205-11e8-9eb0-1d37dbf44659.png)

 I'm not really sure how I feel about it.

**Comment by Centril** [comment]
> * The dark grey is almost exactly the same colour as the comment background in the [GitHub dark theme](https://userstyles.org/styles/37035/github-dark). Admittedly other logos, including the Rust logo itself, have the same issue.

Maybe that's an illustrator thing? I picked the first color in illustrator that made sense to me =P

> * I think the problem with the "whoosh" is that it's the only curved element in the design despite being a minor element. It's also attached to the P which makes it look more like hair to me. Straight lines not connected to the body might work ([example](https://upload.wikimedia.org/wikipedia/commons/2/23/Go_Logo_Aqua.svg)).

Someone mentioned this on Discord as well that it looked like "old man hair" ;) I think the "woosh" design is three strikes and out. Here's one based on the straight lines ideas:

![proptest4-wind](https://user-images.githubusercontent.com/855702/48133584-97d41d80-e297-11e8-8f0d-770af3e74ead.png)

![proptest3-wind](https://user-images.githubusercontent.com/855702/48133716-10d37500-e298-11e8-8a0f-69eb6aae74ea.png)

> I'm not really sure how I feel about it.

It's clearly more Rust-y but also somewhat less timeless;

Here's a version that has more straight lines:

![proptest7-wind](https://user-images.githubusercontent.com/855702/48143401-01abf180-e2af-11e8-9e9e-8af878fb486b.png)


![proptest6-wind](https://user-images.githubusercontent.com/855702/48143066-5438de00-e2ae-11e8-89a2-bf2ab1b7e01a.png)

(The "cogs" are probably not perfectly aligned...)

**Comment by matthew-russo** [comment]
Closing this one out as we don't have any immediate plans for a logo. If that changes we'll open a new issue
