### ISSUE TITLE
Support building on webassembly

### ISSUE THREAD

**Issue by detrumi** [proptest-rs/proptest#137]
It would be great if proptest could be built on WASM. Slightly related to #47 but more specific, since proptest can almost be compiled to webassembly already.

I'm already disabling [the default forking feature](https://altsysrq.github.io/proptest-book/proptest/forking.html), to avoid the `rusty-fork` dependency.

The only thing blocking building proptest on webassembly is [these few lines](https://github.com/AltSysrq/proptest/blob/d1c4b049337d2f75dd6f49a095115f7c532e5129/proptest/src/arbitrary/_std/env.rs#L89), importing `std::os::unix` inside a `#[cfg(not(target_os = "windows"))]` block.

Could the `osstring_invalid_string` function be constrained more, by excluding `wasm32` for example? Or maybe there's a better solution to avoid using `std::os::unix` on all non-windows targets?

**Comment by matklad** [comment]
A possible solution here would be to split proptest into two crates:

* a `proptest-traits`, which exposes strategy trait and related machinery. This part could be strictly pure & platform-independent I think?
* `proptest-runner`, which allows one to actually run property test, maintaining a failure database, etc.

**Comment by AltSysrq** [comment]
I gated the [code you deleted](https://github.com/detrumi/proptest/commit/c3a2555fe74419238c7d9d364936504ddb84f32c) behind a `cfg` check in 0.9.2, so I think it should be working for you now.

> split proptest into two crates

Unfortunately, the two are rather intertwined — even the basic public API requires `Strategy` to know about `TestRunner` and vice versa.

**Comment by lastmjs** [comment]
Were any of you able to get proptest to compile for WebAssembly? I am running into this error:

```bash
error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /home/lastmjs/.cargo/registry/src/github.com-1ecc6299db9ec823/wait-timeout-0.2.0/src/lib.rs:66:9
   |
66 |         imp::wait_timeout(self, dur)
   |         ^^^ use of undeclared crate or module `imp
```

**Comment by lastmjs** [comment]
I turned off all features except for std, and it now compiles.

Have you had success actually getting proptest to run? I keep getting a panic when trying to create a runner: `Panicked at 'not supported on this platform', library/std/src/sys/wasm/../unsupported/os.rs:76:5`

**Comment by RReverser** [comment]
^ that's about how far I got too, with a more precise message in a few places:

> panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/locks/condvar.rs:23:9

**Comment by mlodato517** [comment]
I tried a minimal reproduction with [`wasm-pack` and `wasm_bindgen_test`](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html) like:
```rust
proptest! {
    #[wasm_bindgen_test]
    fn some_test(num: u32) { assert_eq!(num, num); }
}
```

And ran into three failures:
- Two were usages of [`Instant::now` in `runner.rs`](https://github.com/proptest-rs/proptest/blob/658d5130e72bd14290d7c15f7affb38cda66522e/proptest/src/test_runner/runner.rs#L253). Not sure if those can/should be grouped under the `timeout` feature. If so, that'd be convenient and I'd happy to PR that.
- The other one was [env vars in the config](https://github.com/proptest-rs/proptest/blob/658d5130e72bd14290d7c15f7affb38cda66522e/proptest/src/test_runner/config.rs#L83-L85) and I have no idea what to do about that :sweat_smile: 

Neither of these address the more niche cases like `condvar` mentioned above but maybe we can iteratively approach WASM support by handling something like that minimal reproduction first? Happy to help if anyone has bandwidth to offer any guidance!
