### ISSUE TITLE
proptest book doc examples appear broken

### ISSUE THREAD

**Issue by justanotherdot** [proptest-rs/proptest#158]
Hi! 👋 

Was going through the proptest book today and noticed several of the examples won't run and spew out compile errors into the output; see attached image:

![image](https://user-images.githubusercontent.com/5350032/61101875-eaad4700-a4ae-11e9-951e-9d6169b4a851.png)

**Comment by AltSysrq** [comment]
Somehow I didn't know that that feature existed. I will try to fix it soon.
