### ISSUE TITLE
Minor: book is not mentioned anywhere in README or the github page

### ISSUE THREAD

**Issue by aldanor** [proptest-rs/proptest#218]
It would be nice if the book was mentioned somewhere in the first pages of README and/or in the repo description with a link?

Currently it's not immediately obvious the book even exists when opening the repository page (other that seeing 'book').

**Comment by aldanor** [comment]
As a matter of fact, there's no immediate link to `docs.rs` either, might be nice to add it as one of the badges in the readme? (and/or repo description)

**Comment by matthew-russo** [comment]
Both the API docs and the book are currently linked as badges:
https://github.com/proptest-rs/proptest/blob/master/proptest/README.md?plain=1#L6-L10

I've added a section to the top of the README explicitly mentioning the book:
https://github.com/proptest-rs/proptest/pull/309
