### ISSUE TITLE
`bytes_regex()` only allows regexs that match valid UTF-8

### ISSUE THREAD

**Issue by hkratz** [proptest-rs/proptest#238]
Proptests trying to generate invalid UTF-8 sequences with `bytes_regex()` result in an error.

Source:
```rust
proptest! {
    #[test]
    fn simple_invalid_prop(ref input in bytes_regex(r"(?-u)\xFF").unwrap()) {
    }
}
```
Error:
```
---- tests::simple_invalid_prop stdout ----
thread 'tests::simple_invalid_prop' panicked at 'called `Result::unwrap()` on an `Err` value: RegexSyntax(Translate(Error { kind: InvalidUtf8, pattern: "(?-u)\\xFF", span: Span(Position(o: 5, l: 1, c: 6), Position(o: 9, l: 1, c: 10)) }))', src\tests.rs:239:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This makes them much less useful in practice. Maybe creating a parser with [`regex_syntax::ParserBuilder::allow_invalid_utf8()`](https://docs.rs/regex-syntax/0.6.25/regex_syntax/struct.ParserBuilder.html#method.allow_invalid_utf8) set to true is sufficient to fix this.

**Comment by zackw** [comment]
Whoops, this is exactly the same as #336.  I should have looked more carefully at the issue list before filing that one.

**Comment by matthew-russo** [comment]
closing this as duplicate. #336 will be used for tracking
