### ISSUE TITLE
Add entry in guide on how to implement `Arbitrary` (without derive)

### ISSUE THREAD

**Issue by jorgecarleitao** [proptest-rs/proptest#252]
It would be useful to have an implementation in the book, even if for a single struct, to understand how this trait should be implemented.

**Comment by cameron1024** [comment]
Hi, apologies for the long delay, there's new maintainers now and we're going through old issues. I've added a section, feel free to comment on the PR if the example is confusing 😁

**Comment by seanmajorpayne** [comment]
Closing this issue since it is resolved and stale.
