### ISSUE TITLE
`prop_assert_ne!` requires `prop_assert!` to be imported

### ISSUE THREAD

**Issue by TopGunSnake** [proptest-rs/proptest#256]
https://github.com/AltSysrq/proptest/blob/bc2d867a7cd06060e0b565b72fce1d94cc2fe943/proptest/src/sugar.rs#L826
https://github.com/AltSysrq/proptest/blob/bc2d867a7cd06060e0b565b72fce1d94cc2fe943/proptest/src/sugar.rs#L778

In contrast to prop_test_eq!, which references the prop_assert! macro via `$crate::prop_assert!`, prop_test_ne! references uses the prop_assert! with no prefix. This requires `use proptest::prop_assert` to be added to user test code for the prop_test_ne! macro to , unlike the prop_test_eq! macro.

Example error when testing:
```
error: cannot find macro `prop_assert` in this scope                                                                    
   --> src\enigma.rs:40:13
    |
40  |             prop_assert_ne!(input, cipher_text);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a macro with a similar name exists: `prop_assert_eq`
    |
   :::PATH\proptest-1.0.0\src\sugar.rs:774:1
    |
774 | macro_rules! prop_assert_eq {
    | --------------------------- similarly named macro `prop_assert_eq` defined here
    |
    = note: consider importing this macro:
            proptest::prop_assert
    = note: this error originates in the macro `prop_assert_ne` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `enigma-machine` due to previous error
```

**Comment by schuelermine** [comment]
I have run into this problem as well
