### ISSUE TITLE
Test failures since switch to rand 0.8

### ISSUE THREAD

**Issue by plugwash** [proptest-rs/proptest#258]
I am investigating upgrading the rust packaging in Debian to rand 0.8 and I have noticed that proptest seems to suffer from test failures since it switched to rand 0.8.

cargo test -p proptest --lib

failures:

---- num::test::contract_sanity::f32::range_from stdout ----
thread 'num::test::contract_sanity::f32::range_from' panicked at 'Uniform::new_inclusive: range overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.8.4/src/distributions/uniform.rs:996:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- num::test::contract_sanity::f32::range_to_inclusive stdout ----
thread 'num::test::contract_sanity::f32::range_to_inclusive' panicked at 'Uniform::new_inclusive: range overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.8.4/src/distributions/uniform.rs:996:1

---- num::test::contract_sanity::f64::range_from stdout ----
thread 'num::test::contract_sanity::f64::range_from' panicked at 'Uniform::new_inclusive: range overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.8.4/src/distributions/uniform.rs:997:1

---- num::test::contract_sanity::f64::range_to_inclusive stdout ----
thread 'num::test::contract_sanity::f64::range_to_inclusive' panicked at 'Uniform::new_inclusive: range overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.8.4/src/distributions/uniform.rs:997:1

failures:
    num::test::contract_sanity::f32::range_from
    num::test::contract_sanity::f32::range_to_inclusive
    num::test::contract_sanity::f64::range_from
    num::test::contract_sanity::f64::range_to_inclusive

test result: FAILED. 1421 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 783.81s

error: test failed, to rerun pass '-p proptest --lib'

I can reproduce the failures with commit commit  bc2d867a7cd06060e0b565b72fce1d94cc2fe943 (current HEAD) and commit 291908ac22a4c05f9fcad31cb460c502723b22ae (the first commit to use rand 0.8) and but not with 37dba3abe9aa0a1cc6b9762353bf6dd89b9ef6a5 (the last commit to use rand 0.7)

Ideally I'd like to see a fix for this issue, but if that is not possible, i'd at least like an opinion on how serious these failures are so I can decide whether they should block Debian's transition to rand 0.8.

**Comment by mikerite** [comment]
It's 0.8.4 in particular. The reason seems to be this change: https://github.com/rust-random/rand/pull/1108 .

**Comment by plugwash** [comment]
Hmm, yes thanks for the link, so it seems that the rand guys didn't consider a change from dodgy results to a panic to be a semver-breaking change.

That still leaves the question of how to address this? is this likely to break actual users of proptest? is there a way to disable/modify the tests only for floating point types?

**Comment by plugwash** [comment]
For what it's worth, after testing reverse dependencies I decided that these failures were not significant enough to block the rand transition in Debian and disabled the tests in question.

**Comment by russelldb** [comment]
This is very blocking for me. I get the error all the time. Does #261 fix?
