### ISSUE TITLE
impl Arbitrary for PathBuf

### ISSUE THREAD

**Issue by nipunn1313** [proptest-rs/proptest#272]
I see here - there's a TODO remaining.
I'd find it helpful in my project!
https://github.com/proptest-rs/proptest/blob/master/proptest/src/arbitrary/_std/path.rs

**Comment by EricCrosson** [comment]
The `PathBuf` arbitrary was implemented in https://github.com/proptest-rs/proptest/pull/368 -- this issue can be closed 🎉
