### ISSUE TITLE
Is it possible to run a test for particular seed?

### ISSUE THREAD

**Issue by Yamp** [proptest-rs/proptest#277]
On case of test failure hypothesis suggests to add decorator @reproduce_faliure("<seed>") to easily reproduce and debug a particular failure. This is very convenient for the usual pipeline Test -> Fix failure with debugger -> Look for the next failures. 

Do we have something similar? Or can we add this functionality?

**Comment by matthew-russo** [comment]
There are a couple options.

proptest will persist the seeds of failing tests by default. It will also re-run these seeds on every execution before new seeds are generated to ensure once a failure is found, your code won't regress in the future. If you're running tests locally, this is pretty easy as the file will be generated locally and you can just commit it along with your fix. If this is in a CI environment, you'd need a way to maintain access to the file from a failed run and copy it over to your repository. You can read a bit more about this in [the book](https://altsysrq.github.io/proptest-book/proptest/failure-persistence.html?highlight=seed#failure-persistence)
**Note**: you can *disable* persistence via [`Config::failure_persistence`](https://docs.rs/proptest/latest/proptest/test_runner/struct.Config.html#structfield.failure_persistence), [configuring proptest in the book](https://altsysrq.github.io/proptest-book/proptest/tutorial/config.html)

Alternatively you can construct a TestRunner with a particular seed using [`TestRunner::new_with_rng`](https://docs.rs/proptest/latest/proptest/test_runner/struct.TestRunner.html#method.new_with_rng) with an rng instance constructed via [`TestRng::from_seed`](https://docs.rs/proptest/latest/proptest/test_runner/struct.TestRng.html#method.from_seed) and then you can use the TestRunner to run any tests you want with that seed using [`TestRunner::run`](https://docs.rs/proptest/latest/proptest/test_runner/struct.TestRunner.html#method.run). This allows you to programmatically set up your test harness however you want if you have more bespoke requirements.

Let me know if this helps!

**Comment by matthew-russo** [comment]
Closing this as it hasn't had any activity. If there are further questions feel free to reopen or open a new issue
