### ISSUE TITLE
Testing a small number of cases across a large number of CI runs

### ISSUE THREAD

**Issue by adeschamps** [proptest-rs/proptest#290]
I have some tests that are a little slow. Some are integration tests that take on the order of a few seconds, although even tests that take ~10ms still add up when many iterations are tested.

During development, I like to explore as much of the input space as possible, and I'm happy to set `PROPTEST_CASES` to a large number and let it run in the background. But once I'm satisfied with my code, my priorities shift to not slowing down CI too much. Since CI runs frequently, could I configure it to test just a few cases and still expect that over the course of many CI runs, the input space will still be explored?

Put another way, if I run a single test with the default value of `PROPTEST_CASES=256`, compared to 256 CI runs where `PROPTEST_CASES=1`, can I expect similar coverage?

**Comment by rex-remind101** [comment]
I think this is a harder question to provide a complete answer for than it seems on the surface. If your test is over a function those interface is just scalar arguments, then default strategies will randomly sample within consistent bounds of those scalar arguments. In that case, coverage of 1 test (run * 256 cases) == (256 test runs * 1 case). With more complex testing strategies and implementations that may have nonlinear characteristics (such as where there's memoization is included), I'm not those runs will be exactly equal random variables.

**Comment by rex-remind101** [comment]
For full disclosure I am a new maintainer here so I'll need to think about this more, there may be a simple answer for all cases and not just basic scalar cases. If someone else has that answer already feel free to provide it.

**Comment by adeschamps** [comment]
Thanks for the response! In my tests I don't have any memoization or state -- it's all scalars and collections.

If I'm reading the code correctly (and also based on my observations when running the tests) it seems like one thing to be aware of is the saved seeds from a regressions file. Since the runner runs those first, and they count towards the number of cases run, I believe that if I were to set `PROPTEST_CASES <= num_regressions` then the runner would never explore new inputs. This is something I can work around -- for example, by not committing the regressions file, and instead converting regressions into separate unit tests.

**Comment by rex-remind101** [comment]
> If I'm reading the code correctly (and also based on my observations when running the tests) it seems like one thing to be aware of is the saved seeds from a regressions file.

This seems like a bug given this.
https://github.com/proptest-rs/proptest/blob/1ad340e7c2276d0afc4c0ac13040a1861d198895/proptest/src/test_runner/config.rs#L182-L186

and I'm guessing you're referring to this in the code https://github.com/proptest-rs/proptest/blob/00f29af8e8138d4f58e592a1362bec1715733a41/proptest/src/test_runner/runner.rs#L656

I'll take a look at that separately, thanks for pointing that out!

**Comment by rex-remind101** [comment]
@adeschamps fix merged and new release pushed. Thanks for taking the time to point out that issue.
