### ISSUE TITLE
Docs referencing non-existing function `TestRunner::set_source_file`

### ISSUE THREAD

**Issue by matusf** [proptest-rs/proptest#293]
The function `TestRunner::set_source_file` does not exists

https://github.com/proptest-rs/proptest/blob/00f29af8e8138d4f58e592a1362bec1715733a41/proptest/src/test_runner/failure_persistence/file.rs#L42

**Comment by matthew-russo** [comment]
Thanks for the report. Some quick context for future work -- i think this method was replaced by [`Config::with_source_file`](https://docs.rs/proptest/latest/proptest/test_runner/struct.Config.html#method.with_source_file) but we can probably just remove this line from the docs as the place to set the value isn't very relevant for the purpose of the value
