### ISSUE TITLE
Please update CHANGELOG for 1.1.0

### ISSUE THREAD

**Issue by davidhewitt** [proptest-rs/proptest#302]
Thanks for taking on releasing a new version of this crate!

I was hoping to read a summary of the changes released in 1.1.0.

I looked at https://github.com/proptest-rs/proptest/blob/master/proptest/CHANGELOG.md, but that doesn't appear to have any released entries past 1.0.

Would you be willing to update this please?

**Comment by matthew-russo** [comment]
oh my sorry about that! i've opened a PR to update the changelog. thanks for bringing it to our attention!

**Comment by davidhewitt** [comment]
Thanks 😃
