### ISSUE TITLE
Ability to guard branches of `prop_oneof!`

### ISSUE THREAD

**Issue by jonhoo** [proptest-rs/proptest#305]
I'm running into a case where some of the cases of `prop_oneof!` are only viable for a subset of inputs. Specifically, I have an `arb` that generates the right-hand side of `[features]` specifiers in a `Cargo.toml`:
```rust
fn arb_feature(
    deps: Arc<[Dependency]>,
    base_features: Arc<[String]>,
    current_feature: usize,
) -> impl Strategy<Value = FeatureSpec> {
    let ndeps = deps.len();
    prop_oneof![
        // A feature spec can reference another feature
        (0..base_features.len()).prop_filter_map(
            "features cannot depend on themselves",
            move |i| {
                if i == current_feature {
                    return None;
                }
                Some(FeatureSpec::Feature(base_features[i].clone()))
            }
        ),
        // Or it can reference a dependency or a feature of a dependency
        (0..ndeps, arb_maybe_feature_name()).prop_map(move |(i, ft)| {
            match ft {
                None => FeatureSpec::Dep(deps[i].0.clone()),
                Some(ft) => FeatureSpec::Weak(deps[i].0.clone(), ft),
            }
        })
    ]
}
```
The code above fails because of too many local rejections. This makes sense since there are often few features (I only generate `0..3` of them), and so if we're picking an arbitrary feature from the list we're relatively likely to pick the same feature, which isn't allowed. I tried to change the generation to `0..(base_features.len()-1))`, but this runs into trouble when there is only one feature.

What I _really_ want here is the ability to say that the first branch should only be considered if there are at least two features. And similarly for the second branch, I want to say that it should only be considered when there is at least one dependency (currently it'll crash if that's the case — I have yet to fix that). And only if no branches are feasible would I want it to do a local rejection.

**Comment by jonhoo** [comment]
I suppose maybe the argument here is that I should instead branch on `deps.len()` and `base_features.len()` and return `.boxed()` strategies in each arm?

**Comment by jonhoo** [comment]
For reference, here's what I ended up with:
https://github.com/jonhoo/cargo-index-transit/blob/3188d1fb8e9ccb258d61ef20136d317ff5ba5bad/tests/proptest.rs#L177-L195

**Comment by rex-remind101** [comment]
Sorry for the delayed response. If there's some per-determined branching that you need to do I would recommend specifying that clearly and pattern matching as it seems you did. Is there more you need help with?

**Comment by jonhoo** [comment]
Well, so, it's a little awkward here because there's essentially only a subset of the generated options that are "legal", and I couldn't find a good way to represent that. What I linked to above is the closest I could get, but it's pretty convoluted. I was hoping there would be a slightly more ergonomic way to achieve a similar outcome.

Nothing directly actionable here I suppose, more of a "I wish this pattern had a more ergonomic solution".

**Comment by jonhoo** [comment]
That sounds like exactly the kind of thing I'd want, you're right!

**Comment by matthew-russo** [comment]
We've released proptest-state-machine so I'm going to close this. Feel free to reopen if there is a specific ask related to `prop_oneof!`
