### ISSUE TITLE
Equivalent of `hypothesis.example`?

### ISSUE THREAD

**Issue by matthiasgoergens** [proptest-rs/proptest#330]
It's sometimes useful to add specific examples to test in addition to your generators.

Python's Hypothesis has [`hypothesis.example`](https://hypothesis.readthedocs.io/en/latest/reproducing.html#hypothesis.example) for that.  What's our equivalent, if any?

If we don't have an equivalent, I can help add it, if you can give me some pointers for getting started.  Thanks!

**Comment by matthew-russo** [comment]
We don't currently have an equivalent but its requested in #284 and I've done a little bit of work towards in. I'm hoping to build on top of the proc macro attribute that's currently being worked on.

The goal is to make it an open API that could potentially be used for clean integrations with similar crates such as `rstest` if someone doesn't want to use the built-in support. Unfortunately i don't have clear timelines on when we'd expect to get this in.

If its fine with you, I'll go ahead and close this issue and you can track progress on #284
