### ISSUE TITLE
Use prop_assume under prop_compose?

### ISSUE THREAD

**Issue by akiradeveloper** [proptest-rs/proptest#334]
Hello.

I want to use `prop_assume` filtering under `prop_compose` but it seems to be designed to be used under `proptest` only.

How do I use filtering under `prop_compose`?

**Comment by tzemanovic** [comment]
hi, one option is to use `prop_filter`/`prop_filter_map` method on a `Strategy`. Because `prop_assume` macro returns a `Result` it cannot be used in `prop_compose` that returns a `Strategy`

**Comment by akiradeveloper** [comment]
@tzemanovic I see. Thank you.
