### ISSUE TITLE
Idea: Making a book and splashy website about proptest

### ISSUE THREAD

**Issue by Centril** [proptest-rs/proptest#36]
Some inspiration:
+ serde.rs <-- for books
+ tokio.rs
+ rocket.rs <-- this just looks amazing.

**Comment by Centril** [comment]
For now I've registered `proptest.rs` with `istanco.com` and setup DNS as follows:

| Name         | Type      | TTL | Target |
| ------------|---------| -----|-------|
| proptest.rs | A           | 300 | 192.30.252.154 |
| proptest.rs | A           | 300 | 192.30.252.153 |
| www          | CNAME | 300 | proptest.github.io |
| proptest.rs | NS         | 300 | ns1.istanco.com |
| proptest.rs | NS         | 300 | ns2.istanco.com |

**Comment by AltSysrq** [comment]
I would have preferred if you hadn't spent your money predicated on me making a decision.

> a book

What would you suggest would go here? The longer tutorials would be a good fit I suppose, but is there a good way to do that without loosing easy testability of the examples?

> splashy website

I'm personally not a big fan of these. I'm also utterly incompetent at making websites. If you want to go ahead and put something together though, go ahead.

**Comment by Centril** [comment]
> I would have preferred if you hadn't spent your money predicated on me making a decision.

Hehe =P I got carried away ;)

I think we should initially start with just having a gh-pages site that just contains `cargo doc` stuff and then we can make something better later.

> What would you suggest would go here?

As you say.. the longer tutorials, which would include notes on how you use custom derive, more case studies (longer examples), etc. I think `serde.rs` is what we should aspire too with the book, it seems pretty nice.

It seems that mdBook supports running tests: https://rust-lang-nursery.github.io/mdBook/cli/test.html

> I'm personally not a big fan of these. I'm also utterly incompetent at making websites. If you want to go ahead and put something together though, go ahead.

I'm pretty decent at design (I think..), but I haven't done any web programming for some time. But that would give me a great reason to write some code using rocket.rs ;)
But let's make a great book first which I'd be happy to work on ^,-

**Comment by AltSysrq** [comment]
> mdBook supports running tests

Good to know.

> let's make a great book first

Sounds good to me. I unfortunately have some other stuff going on at the moment so I probably won't be able to do any serious work, but if you get something on a PR I can definitely review+merge. Hopefully things will be back to normal for me by next week though.

**Comment by matthew-russo** [comment]
Closing this one as the book is published here: https://altsysrq.github.io/proptest-book/intro.html
and we don't have any immediate plans for a website. If there are additional suggestions feel free to open a new issue
