### ISSUE TITLE
Proptest with Rust 1.72 produces clippy::arc_with_non_send_sync warnings

### ISSUE THREAD

**Issue by sunshowers** [proptest-rs/proptest#364]
The warnings appear to be because we generate `Arc<BoxedStrategy<T>>` sometimes, and come from the following places that I could see:

- [x] The `prop_oneof!` macro: https://github.com/proptest-rs/proptest/pull/363
- [x] proptest-derive: https://github.com/proptest-rs/proptest/pull/365

**Comment by matthew-russo** [comment]
#363 and #365 merged. Thanks!
