### ISSUE TITLE
Release proptest-derive 0.4.0?

### ISSUE THREAD

**Issue by messense** [proptest-rs/proptest#366]
The [crates.io 0.3.0 version](https://crates.io/crates/proptest-derive) still uses syn 0.15 causes duplicate `syn` in dependencies tree.

```
syn v0.15.44 (*)

syn v1.0.109 (*)

syn v2.0.29 (*)
```

**Comment by matthew-russo** [comment]
I'll try to get a release out this weekend.

**Comment by matthew-russo** [comment]
`proptest-derive` 0.4.0 is now published:
https://crates.io/crates/proptest-derive
