### ISSUE TITLE
Update regex-syntax to 0.8

### ISSUE THREAD

**Issue by JustusFluegel** [proptest-rs/proptest#379]
Update regex-syntax to 0.8 and regex to the corresponding version. This would be nice as proptest is the only crate that still requires regex-syntax v0.7 in some of my projects and I would appreciate not having to compile it in that version anymore.

I would also be open to try to create a pr but I am not very familiar with the proptest codebase  so I don't know how that would go. Feel free to tell me if that is welcome tho.

**Comment by matthew-russo** [comment]
Addressed with:
https://github.com/proptest-rs/proptest/pull/386
