### ISSUE TITLE
Attribute macro #[property_test] available in docs, but undocumented and behind undocumented feature

### ISSUE THREAD

**Issue by Andlon** [proptest-rs/proptest#473]
Is the new `#[property_test]` attribute still WIP? It's listed on [docs.rs](https://docs.rs/proptest/latest/proptest/attr.property_test.html), but it has no documentation, and it also appears to be behind an undocumented `attr_macro` feature flag.

It's unclear to me if it was accidentally made public, or if it's missing documentation.

**Comment by rexmas** [comment]
thank you for raising this! the macro is ready to be used, though it is below a version 1. the crate may be found here https://crates.io/crates/proptest-macro
