### ISSUE TITLE
How to convert `SizeRange` to a regular `Range`?

### ISSUE THREAD

**Issue by cospectrum** [proptest-rs/proptest#492]
Using start/end/end_incl/... manually can lead to errors.
Found `frunk::Generic` trait implementation for `SizeRange`, but feature is not documented.
I use my own function. Sad.

**Comment by matthew-russo** [comment]
Are you just looking for a `From<SizeRange> for Range` impl?

**Comment by cospectrum** [comment]
Yes, trait or helper method would be useful
