### ISSUE TITLE
How to use prop_assert_eq in a helper test function?

### ISSUE THREAD

**Issue by incertia** [proptest-rs/proptest#502]
Let's suppose I have a helper function designed to test a specific implementation of a trait.

```rust
fn test_trait<T: MyTrait>() { /* ... */ }

proptest! {
  #[test]
  fn test_struct1() {
    test_trait::<Struct1>();
  }

  #[test]
  fn test_struct2() {
    test_trait::<Struct2>();
  }
}
```

What is the correct way to call prop_assert_eq! in the helper function?

**Comment by matthew-russo** [comment]
Did you end up figuring out how to structure things? Is there anything we can help with?
