### ISSUE TITLE
FYI: Proptesting CLI apps

### ISSUE THREAD

**Issue by Centril** [proptest-rs/proptest#75]
@killercup and I discussed a bit about using `proptest` to test CLI apps which we've recorded at: https://github.com/rust-lang-nursery/cli-wg/issues/43

Filing this issue to make y'all aware of this in case you have ideas ;)

**Comment by bionicles** [comment]
thank you, this is exactly what i'm trying to do right now!

**Comment by bionicles** [comment]
ruh roh... link broke

**Comment by matthew-russo** [comment]
Given the link died I'm going to close this out since I don't know the context of original issue and its been a few years. If there is still some desire for CLI specific support in proptest feel free to open a new issue.
